const palabrasComunes = {
    categoria1: new Set(["yo", "vos", "ella", "nosotros", "nosotras", "usted", "tu", "ustedes", "ellos", "ellas", "a", 
        "ante", "bajo", "contra", "de", "en", "entre", "hacia", "hasta", "para", "por", "según", "durante", "mediante", 
        "sobre", "sin", "tras", "con", "que", "y", "o", "pero", "si", "no", "el", "él", "la", "los", "las", "lo", "un", "una", "unos"]),
    categoria2: new Set(["xq", "pq", "x", "ns", "a", "e", "q", "s", "c", "m", "n", "t", "d", "tmb"]),
    categoria3: new Set(["lo", "te", "me", "ah", "ay", "mi", "es", "se", "un", "una", "re", "como", "eso", "las", "los",
        "le", "ya", "algo", "se", "sé", "cómo", "qué", "más", "mas", "muy", "al", "ni", "esta", "está", "del", "asi", "así",
        "hay", "nos"]),
    categoria4: new Set([
            "de", "Y", "el", "la", "en", "a", "que", "los", "se", "que", "un", "las", "con", "no", "por", 
            "una", "para", "su", "es", "como", "me", "más", "le", "lo", "o", "pero", "sus", "si", "este", 
            "sobre", "entre", "cuando", "también", "todo", "era", "fue", "esta", "ya", "son", "mi", "sin", 
            "la", "años", "ser", "nos", "te", "qué", "dos", "está", "muy", "desde", "porque", "yo", "hasta", 
            "había", "hay", "tiene", "ese", "todos", "hacer", "donde", "eso", "puede", "parte", "vida", 
            "uno", "esa", "tiempo", "él", "ella", "sólo", "dijo", "cada", "vez", "ni", "otro", "después", 
            "otros", "mismo", "hace", "ahora", "les", "estaba", "así", "bien", "e", "día", "año", "aunque", 
            "durante", "país", "siempre", "otra", "tres", "algo", "ver", "mundo", "los", "tan", "antes", 
            "sí", "cómo", "casa", "nada", "trabajo", "estos", "momento", "quien", "están", "gran", "esto", 
            "forma", "mayor", "personas", "ellos", "nacional", "gobierno", "sino", "primera", "unos", 
            "hacia", "tenía", "entonces", "hoy", "lugar", "ante", "luego", "estado", "otras", "días", 
            "tener", "pues", "va", "contra", "nunca", "casi", "tienen", "según", "algunos", "una", "manera", 
            "nuevo", "además", "hombre", "millones", "dar", "mucho", "veces", "menos", "todas", "primer", 
            "presidente", "decir", "mujer", "tu", "solo", "mientras", "cosas", "mí", "debe", "tanto", "aquí", 
            "estas", "ciudad", "fueron", "historia", "más", "sin embargo", "toda", "tras", "pueden", "dice", 
            "tipo", "las", "grupo", "cual", "social", "gente", "sistema", "desarrollo", "mejor", "noche", 
            "misma", "estar", "lado", "muchos", "sea", "cuenta", "mujeres", "agua", "importante", "aún", 
            "dentro", "cuatro", "información", "mis", "madre", "salud", "nuestro", "será"]),
};
